### PR TITLE
fix parse methods

### PR DESCRIPTION
**Pull request by ptcong**

### CODE REVIEW

**Comment by erichard** [comment]
@ptcong Could you provide a before/after example ?

**Comment by ptcong** [comment]
Sometimes you want to override parent methods

```
class A {
public function a1() {
....
}
}
class B extends A {

}
```
this fix to match `public function a1() {`
```
pattern = "(?<!\* )(?:abstract )?((?:public|protected|private)(?: static)?\s+function\s+[\w]+\s*\(.*?\))(?:\s*;|.*?{)"'
```

**Comment by ptcong** [comment]
@erichard don't you like this PR ?

**Comment by erichard** [comment]
@ptcong Thanks !

**Pull request merged**
